.script_template: &script_template
  - set -euo pipefail

.test_script_template: &test_script_definition
  - pip install -e .[tests]
  # Use --no-warn-unused-ignores while following issue is not fixed
  # https://github.com/python/mypy/issues/8823
  - mypy --python-executable "$(which python)" -p antenna.security --no-warn-unused-ignores
  - time catchsegv python -m unittest discover -s tests

stages:
  - test

test:python36:
  image: python:3.6-buster
  before_script:
    - *script_template
  script:
    - *test_script_definition

test:python37:
  image: python:3.7-buster
  before_script:
    - *script_template
  script:
    - *test_script_definition

test:python38:
  image: python:3.8-buster
  before_script:
    - *script_template
  script:
    - *test_script_definition

test:python39:
  image: python:3.9-buster
  before_script:
    - *script_template
  script:
    - *test_script_definition
