.script_template: &script_template
  - set -euo pipefail

.test_script_template: &test_script_definition
  - pip install -e .[tests]
  - mypy -p antenna.security
  - python -m unittest discover -s tests

stages:
  - test

test:python36:
  image: python:3.6-buster
  before_script:
    - *script_template
    - apt-get -y install build-essential
  script:
    - *test_script_definition

test:python37:
  image: python:3.7-buster
  before_script:
    - *script_template
    - apt-get -y install build-essential
  script:
    - *test_script_definition

test:python38:
  image: python:3.8-buster
  before_script:
    - *script_template
    - apt-get -y install build-essential
  script:
    - *test_script_definition

test:python39:
  image: python:3.9-buster
  before_script:
    - *script_template
    - apt-get -y install build-essential
  script:
    - *test_script_definition
