.test_script_template: &test_script_definition
  - set -euo pipefail
  - pip install -U pip setuptools wheel mypy
  - pip install .
  # Use --no-warn-unused-ignores while following issue is not fixed
  # https://github.com/python/mypy/issues/8823
  - mypy --python-executable "$(which python)" --no-warn-unused-ignores .
  - time catchsegv python -m unittest discover -s tests

stages:
  - test

test:python36:
  image: python:3.6-buster
  script:
    - *test_script_definition

test:python37:
  image: python:3.7-buster
  script:
    - *test_script_definition

test:python38:
  image: python:3.8-buster
  script:
    - *test_script_definition

test:python39:
  image: python:3.9-buster
  script:
    - *test_script_definition

test:python310:
  image: python:3.10-buster
  script:
    - *test_script_definition
