name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - id: "builder-python${{ matrix.python }}"
        name: Set up Docker Buildx for python ${{ matrix.python }}
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          builder: ${{ steps.*.outputs.name }}
          context: .
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          cache-from: type=gha
