name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Deps
        run: |
          pip install -U pip mypy wheel setuptools poethepoet
          sed -i 's/type = "auto"/type = "simple"/' pyproject.toml
          poe build
          pip install .

      - name: Mypy
        run: |
          poe mypy

      - name: Test
        run: |
          poe test
